merge of past commits and functioning test with env variable

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,12 +13,23 @@ on:
   pull_request:
     branches: [ main ]
 
+env:
+  browserName: firefox
+
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
     steps:
     - uses: browser-actions/setup-chrome@latest
     - run: chrome --version
+
+    - uses: browser-actions/setup-geckodriver@latest
+    - run: geckodriver --version
+
+    - uses: browser-actions/setup-edge@latest
+    - name: Print Edge version
+      run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion
+
     - uses: actions/checkout@v2
     - name: Set up JDK 17
       uses: actions/setup-java@v2
@@ -27,6 +38,10 @@ jobs:
         distribution: 'zulu'
     - name: Build with Gradle
       run: ./gradlew test --info # Run our tests using Gradle
-    - uses: EnricoMi/publish-unit-test-result-action@v1
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
       with:
-        files: AutomationReport/GoogleSearchTest/*.xml
+        name: Tests            # Name of the check run which will be created
+        path: AutomationReport/GoogleSearchTest/*.xml    # Path to test results
+        reporter: java-junit
